package fasttrackse.ftjd1801.fbms.entity.projectmanage;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Database generated by hbm2java
 */
@Entity
@Table(name = "database", catalog = "project")
public class Database implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idDatabase;
	private String nameDatabase;
	private String note;

	public Database() {
	}

	public Database(String nameDatabase, String note) {
		this.nameDatabase = nameDatabase;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_database", unique = true, nullable = false)
	public Integer getIdDatabase() {
		return this.idDatabase;
	}

	public void setIdDatabase(Integer idDatabase) {
		this.idDatabase = idDatabase;
	}

	@Column(name = "name_database", length = 45)
	@NotNull
	public String getNameDatabase() {
		return this.nameDatabase;
	}

	public void setNameDatabase(String nameDatabase) {
		this.nameDatabase = nameDatabase;
	}

	@Column(name = "note", length = 45)
	@NotNull
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}