package fasttrackse.ftjd1801.fbms.entity.projectmanage;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatabaseProjectId generated by hbm2java
 */
@Embeddable
public class DatabaseProjectId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idProject;
	private Integer idDatabase;


	public DatabaseProjectId() {
	}

	public DatabaseProjectId(Integer idProject, Integer idDatabase) {
		this.idProject = idProject;
		this.idDatabase = idDatabase;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "id_database")
	public Integer getIdDatabase() {
		return this.idDatabase;
	}

	public void setIdDatabase(Integer idDatabase) {
		this.idDatabase = idDatabase;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatabaseProjectId))
			return false;
		DatabaseProjectId castOther = (DatabaseProjectId) other;

		return ((this.getIdProject() == castOther.getIdProject()) || (this.getIdProject() != null
				&& castOther.getIdProject() != null && this.getIdProject().equals(castOther.getIdProject())))
				&& ((this.getIdDatabase() == castOther.getIdDatabase()) || (this.getIdDatabase() != null
						&& castOther.getIdDatabase() != null && this.getIdDatabase().equals(castOther.getIdDatabase())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProject() == null ? 0 : this.getIdProject().hashCode());
		result = 37 * result + (getIdDatabase() == null ? 0 : this.getIdDatabase().hashCode());

		return result;
	}

}
