package fasttrackse.ftjd1801.fbms.entity.projectmanage;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * ProgramingLanguage generated by hbm2java
 */
@Entity
@Table(name = "programing_language", catalog = "project")
public class ProgramingLanguage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idLanguage;
	private String nameLanguage;

	public ProgramingLanguage() {
	}

	public ProgramingLanguage(String nameLanguage) {
		this.nameLanguage = nameLanguage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_language", unique = true, nullable = false)
	public Integer getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(Integer idLanguage) {
		this.idLanguage = idLanguage;
	}

	@Column(name = "name_language", length = 45)
	@NotNull
	public String getNameLanguage() {
		return this.nameLanguage;
	}

	public void setNameLanguage(String nameLanguage) {
		this.nameLanguage = nameLanguage;
	}

}