package fasttrackse.ftjd1801.fbms.entity.projectmanage;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role_all", catalog = "project")
public class RoleAll implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idRole;
	private String role;

	public RoleAll() {
	}

	public RoleAll(String role) {
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_role", unique = true, nullable = false)
	@NotNull
	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	@Column(name = "role", length = 45)
	@NotNull
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
