package fasttrackse.ftjd1801.fbms.entity.quanlithoigian;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * LogTime generated by hbm2java
 */
@Entity
@Table(name = "log_time", catalog = "project")
public class LogTime implements java.io.Serializable {

	private Integer idLog;
	private Integer idEmployee;
	private Integer idProject;
	private String role;
	private Integer time;
	private String describes;
	@DateTimeFormat(iso=ISO.DATE)
	private Date dayLog;
	private String status;

	public LogTime() {
	}

	public LogTime(Integer idEmployee, Integer idProject, String role, Integer time, String describes, Date dayLog,
			String status) {
		this.idEmployee = idEmployee;
		this.idProject = idProject;
		this.role = role;
		this.time = time;
		this.describes = describes;
		this.dayLog = dayLog;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_log", unique = true, nullable = false)
	public Integer getIdLog() {
		return this.idLog;
	}

	public void setIdLog(Integer idLog) {
		this.idLog = idLog;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "id_project")
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "time")
	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	@Column(name = "describes", length = 65535)
	public String getDescribes() {
		return this.describes;
	}

	public void setDescribes(String describes) {
		this.describes = describes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dayLog", length = 10)
	public Date getDayLog() {
		return this.dayLog;
	}

	public void setDayLog(Date dayLog) {
		this.dayLog = dayLog;
	}

	@Column(name = "status", length = 65535)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}