package fasttrackse.ftjd1801.fbms.entity.personnel;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * Certificate generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "certificate", catalog = "project")
public class Certificate implements java.io.Serializable {

	private Integer idCertificate;
	private String typeOfCertificate;
	private String issuedBy;
	@DateTimeFormat(iso=ISO.DATE)
	private Date duration;
	private String note;
	private Integer idEmployee;

	public Certificate() {
	}

	public Certificate(String typeOfCertificate, String issuedBy, Date duration, String note, Integer idEmployee) {
		this.typeOfCertificate = typeOfCertificate;
		this.issuedBy = issuedBy;
		this.duration = duration;
		this.note = note;
		this.idEmployee = idEmployee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_certificate", unique = true, nullable = false)
	public Integer getIdCertificate() {
		return this.idCertificate;
	}

	public void setIdCertificate(Integer idCertificate) {
		this.idCertificate = idCertificate;
	}

	@Column(name = "typeOfCertificate", length = 45)
	public String getTypeOfCertificate() {
		return this.typeOfCertificate;
	}

	public void setTypeOfCertificate(String typeOfCertificate) {
		this.typeOfCertificate = typeOfCertificate;
	}

	@Column(name = "issued_by", length = 45)
	public String getIssuedBy() {
		return this.issuedBy;
	}

	public void setIssuedBy(String issuedBy) {
		this.issuedBy = issuedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "duration", length = 10)
	public Date getDuration() {
		return this.duration;
	}

	public void setDuration(Date duration) {
		this.duration = duration;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "id_employee")
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}
}
