package fasttrackse.ftjd1801.fbms.entity.personnel;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * EmployeeProfile generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "employee_profile", catalog = "project")
public class EmployeeProfile implements java.io.Serializable {

	private Integer idEmployee;
	private String name;
	private Integer sex;
	@DateTimeFormat(iso=ISO.DATE)
	private Date dayOfBirth;
	private String address;
	private String contact;
	private String email;
	private String introduction;
	private String idRights;
	private String note;
	private String idDepartment;
	private Integer dayOfRest;
	private String avatar;

	public EmployeeProfile() {
	}

	public EmployeeProfile(String name, Integer sex, Date dayOfBirth, String address, String contact, String email,
			String introduction, String idRights, String note, String idDepartment, Integer dayOfRest, String avatar) {
		this.name = name;
		this.sex = sex;
		this.dayOfBirth = dayOfBirth;
		this.address = address;
		this.contact = contact;
		this.email = email;
		this.introduction = introduction;
		this.idRights = idRights;
		this.note = note;
		this.idDepartment = idDepartment;
		this.dayOfRest = dayOfRest;
		this.avatar = avatar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_employee", unique = true, nullable = false)
	public Integer getIdEmployee() {
		return this.idEmployee;
	}

	public void setIdEmployee(Integer idEmployee) {
		this.idEmployee = idEmployee;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dayOfBirth", length = 10)
	public Date getDayOfBirth() {
		return this.dayOfBirth;
	}

	public void setDayOfBirth(Date dayOfBirth) {
		this.dayOfBirth = dayOfBirth;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact", length = 30)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "introduction", length = 65535)
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@Column(name = "id_rights", length = 30)
	public String getIdRights() {
		return this.idRights;
	}

	public void setIdRights(String idRights) {
		this.idRights = idRights;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "id_department", length = 30)
	public String getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(String idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Column(name = "dayOfRest")
	public Integer getDayOfRest() {
		return this.dayOfRest;
	}

	public void setDayOfRest(Integer dayOfRest) {
		this.dayOfRest = dayOfRest;
	}

	@Column(name = "avatar", length = 50)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

}
