package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChucDanh generated by hbm2java
 */
@Entity
@Table(name = "chuc_danh", catalog = "project")
public class ChucDanh implements java.io.Serializable {

	private String maChucDanh;
	private String tenChucDanh;

	public ChucDanh() {
	}

	public ChucDanh(String maChucDanh, String tenChucDanh) {
		this.maChucDanh = maChucDanh;
		this.tenChucDanh = tenChucDanh;
	}

	@Id

	@Column(name = "ma_chuc_danh", unique = true, nullable = false, length = 30)
	public String getMaChucDanh() {
		return this.maChucDanh;
	}

	public void setMaChucDanh(String maChucDanh) {
		this.maChucDanh = maChucDanh;
	}

	@Column(name = "ten_chuc_danh", nullable = false)
	public String getTenChucDanh() {
		return this.tenChucDanh;
	}

	public void setTenChucDanh(String tenChucDanh) {
		this.tenChucDanh = tenChucDanh;
	}

}
