package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "project")
public class Department implements java.io.Serializable {

	private Integer idDepartment;
	private String nameDepartment;
	private String quest;
	private String describes;

	public Department() {
	}

	public Department(String nameDepartment, String quest, String describes) {
		this.nameDepartment = nameDepartment;
		this.quest = quest;
		this.describes = describes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_department", unique = true, nullable = false)
	public Integer getIdDepartment() {
		return this.idDepartment;
	}

	public void setIdDepartment(Integer idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Column(name = "name_department", length = 45)
	public String getNameDepartment() {
		return this.nameDepartment;
	}

	public void setNameDepartment(String nameDepartment) {
		this.nameDepartment = nameDepartment;
	}

	@Column(name = "quest", length = 45)
	public String getQuest() {
		return this.quest;
	}

	public void setQuest(String quest) {
		this.quest = quest;
	}

	@Column(name = "describes", length = 65535)
	public String getDescribes() {
		return this.describes;
	}

	public void setDescribes(String describes) {
		this.describes = describes;
	}

}
