package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DocumentCategory generated by hbm2java
 */
@Entity
@Table(name = "document_category", catalog = "project")
public class DocumentCategory implements java.io.Serializable {

	private Integer idCategory;
	private String icons;
	private Integer rights;

	public DocumentCategory() {
	}

	public DocumentCategory(String icons, Integer rights) {
		this.icons = icons;
		this.rights = rights;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_category", unique = true, nullable = false)
	public Integer getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(Integer idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "icons", length = 45)
	public String getIcons() {
		return this.icons;
	}

	public void setIcons(String icons) {
		this.icons = icons;
	}

	@Column(name = "rights")
	public Integer getRights() {
		return this.rights;
	}

	public void setRights(Integer rights) {
		this.rights = rights;
	}

}
