package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoSoNhanVien generated by hbm2java
 */
@Entity
@Table(name = "ho_so_nhan_vien", catalog = "project")
public class HoSoNhanVien implements java.io.Serializable {

	private Integer maNhanVien;
	private String maPhongBan;
	private String maChucDanh;
	private String hoDem;
	private String ten;
	private String anhDaiDien;
	private Date namSinh;
	private int gioiTinh;
	private int maTinhTrangHonNhan;
	private String queQuan;
	private String danToc;
	private String maQuocTich;
	private String noiTamTru;
	private String soDienThoai;
	private String email;
	private String soCmnd;
	private String noiCap;
	private Date ngayCap;
	private int trangThai;

	public HoSoNhanVien() {
	}

	public HoSoNhanVien(String maPhongBan, String maChucDanh, String hoDem, String ten, String anhDaiDien, Date namSinh,
			int gioiTinh, int maTinhTrangHonNhan, String queQuan, String danToc, String maQuocTich, String noiTamTru,
			String soDienThoai, String email, String soCmnd, String noiCap, Date ngayCap, int trangThai) {
		this.maPhongBan = maPhongBan;
		this.maChucDanh = maChucDanh;
		this.hoDem = hoDem;
		this.ten = ten;
		this.anhDaiDien = anhDaiDien;
		this.namSinh = namSinh;
		this.gioiTinh = gioiTinh;
		this.maTinhTrangHonNhan = maTinhTrangHonNhan;
		this.queQuan = queQuan;
		this.danToc = danToc;
		this.maQuocTich = maQuocTich;
		this.noiTamTru = noiTamTru;
		this.soDienThoai = soDienThoai;
		this.email = email;
		this.soCmnd = soCmnd;
		this.noiCap = noiCap;
		this.ngayCap = ngayCap;
		this.trangThai = trangThai;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_nhan_vien", unique = true, nullable = false)
	public Integer getMaNhanVien() {
		return this.maNhanVien;
	}

	public void setMaNhanVien(Integer maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	@Column(name = "ma_phong_ban", nullable = false, length = 30)
	public String getMaPhongBan() {
		return this.maPhongBan;
	}

	public void setMaPhongBan(String maPhongBan) {
		this.maPhongBan = maPhongBan;
	}

	@Column(name = "ma_chuc_danh", nullable = false, length = 30)
	public String getMaChucDanh() {
		return this.maChucDanh;
	}

	public void setMaChucDanh(String maChucDanh) {
		this.maChucDanh = maChucDanh;
	}

	@Column(name = "ho_dem", nullable = false, length = 50)
	public String getHoDem() {
		return this.hoDem;
	}

	public void setHoDem(String hoDem) {
		this.hoDem = hoDem;
	}

	@Column(name = "ten", nullable = false, length = 20)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "anh_dai_dien", nullable = false, length = 100)
	public String getAnhDaiDien() {
		return this.anhDaiDien;
	}

	public void setAnhDaiDien(String anhDaiDien) {
		this.anhDaiDien = anhDaiDien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nam_sinh", nullable = false, length = 10)
	public Date getNamSinh() {
		return this.namSinh;
	}

	public void setNamSinh(Date namSinh) {
		this.namSinh = namSinh;
	}

	@Column(name = "gioi_tinh", nullable = false)
	public int getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "ma_tinh_trang_hon_nhan", nullable = false)
	public int getMaTinhTrangHonNhan() {
		return this.maTinhTrangHonNhan;
	}

	public void setMaTinhTrangHonNhan(int maTinhTrangHonNhan) {
		this.maTinhTrangHonNhan = maTinhTrangHonNhan;
	}

	@Column(name = "que_quan", nullable = false, length = 250)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Column(name = "dan_toc", nullable = false, length = 50)
	public String getDanToc() {
		return this.danToc;
	}

	public void setDanToc(String danToc) {
		this.danToc = danToc;
	}

	@Column(name = "ma_quoc_tich", nullable = false, length = 50)
	public String getMaQuocTich() {
		return this.maQuocTich;
	}

	public void setMaQuocTich(String maQuocTich) {
		this.maQuocTich = maQuocTich;
	}

	@Column(name = "noi_tam_tru", nullable = false, length = 250)
	public String getNoiTamTru() {
		return this.noiTamTru;
	}

	public void setNoiTamTru(String noiTamTru) {
		this.noiTamTru = noiTamTru;
	}

	@Column(name = "so_dien_thoai", nullable = false, length = 11)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "so_cmnd", nullable = false, length = 11)
	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	@Column(name = "noi_cap", nullable = false, length = 50)
	public String getNoiCap() {
		return this.noiCap;
	}

	public void setNoiCap(String noiCap) {
		this.noiCap = noiCap;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_cap", nullable = false, length = 10)
	public Date getNgayCap() {
		return this.ngayCap;
	}

	public void setNgayCap(Date ngayCap) {
		this.ngayCap = ngayCap;
	}

	@Column(name = "trang_thai", nullable = false)
	public int getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(int trangThai) {
		this.trangThai = trangThai;
	}

}
