package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PhongBan generated by hbm2java
 */
@Entity
@Table(name = "phong_ban", catalog = "project")
public class PhongBan implements java.io.Serializable {

	private String maPhongBan;
	private String tenPhongBan;

	public PhongBan() {
	}

	public PhongBan(String maPhongBan, String tenPhongBan) {
		this.maPhongBan = maPhongBan;
		this.tenPhongBan = tenPhongBan;
	}

	@Id

	@Column(name = "ma_phong_ban", unique = true, nullable = false, length = 30)
	public String getMaPhongBan() {
		return this.maPhongBan;
	}

	public void setMaPhongBan(String maPhongBan) {
		this.maPhongBan = maPhongBan;
	}

	@Column(name = "ten_phong_ban", nullable = false)
	public String getTenPhongBan() {
		return this.tenPhongBan;
	}

	public void setTenPhongBan(String tenPhongBan) {
		this.tenPhongBan = tenPhongBan;
	}

}
