package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleId generated by hbm2java
 */
@Embeddable
public class RoleId implements java.io.Serializable {

	private int maRole;
	private String name;

	public RoleId() {
	}

	public RoleId(int maRole) {
		this.maRole = maRole;
	}

	public RoleId(int maRole, String name) {
		this.maRole = maRole;
		this.name = name;
	}

	@Column(name = "ma_role", nullable = false)
	public int getMaRole() {
		return this.maRole;
	}

	public void setMaRole(int maRole) {
		this.maRole = maRole;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleId))
			return false;
		RoleId castOther = (RoleId) other;

		return (this.getMaRole() == castOther.getMaRole())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaRole();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
