package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesId generated by hbm2java
 */
@Embeddable
public class UsersRolesId implements java.io.Serializable {

	private int maTaiKhoan;
	private int maRole;

	public UsersRolesId() {
	}

	public UsersRolesId(int maTaiKhoan, int maRole) {
		this.maTaiKhoan = maTaiKhoan;
		this.maRole = maRole;
	}

	@Column(name = "ma_tai_khoan", nullable = false)
	public int getMaTaiKhoan() {
		return this.maTaiKhoan;
	}

	public void setMaTaiKhoan(int maTaiKhoan) {
		this.maTaiKhoan = maTaiKhoan;
	}

	@Column(name = "ma_role", nullable = false)
	public int getMaRole() {
		return this.maRole;
	}

	public void setMaRole(int maRole) {
		this.maRole = maRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersRolesId))
			return false;
		UsersRolesId castOther = (UsersRolesId) other;

		return (this.getMaTaiKhoan() == castOther.getMaTaiKhoan()) && (this.getMaRole() == castOther.getMaRole());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaTaiKhoan();
		result = 37 * result + this.getMaRole();
		return result;
	}

}
