package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name = "users_roles", catalog = "project")
public class UsersRoles implements java.io.Serializable {

	private UsersRolesId id;

	public UsersRoles() {
	}

	public UsersRoles(UsersRolesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "maTaiKhoan", column = @Column(name = "ma_tai_khoan", nullable = false)),
			@AttributeOverride(name = "maRole", column = @Column(name = "ma_role", nullable = false)) })
	public UsersRolesId getId() {
		return this.id;
	}

	public void setId(UsersRolesId id) {
		this.id = id;
	}

}
