package fasttrackse.ftjd1801.fbms.entity.bytez;
// Generated Dec 26, 2018 8:20:37 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "project", uniqueConstraints = { @UniqueConstraint(columnNames = "ma_nhan_vien"),
		@UniqueConstraint(columnNames = "username") })
public class Users implements java.io.Serializable {

	private Integer maTaiKhoan;
	private String username;
	private String password;
	private int maNhanVien;
	private Integer enabled;

	public Users() {
	}

	public Users(int maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	public Users(String username, String password, int maNhanVien, Integer enabled) {
		this.username = username;
		this.password = password;
		this.maNhanVien = maNhanVien;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_tai_khoan", unique = true, nullable = false)
	public Integer getMaTaiKhoan() {
		return this.maTaiKhoan;
	}

	public void setMaTaiKhoan(Integer maTaiKhoan) {
		this.maTaiKhoan = maTaiKhoan;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ma_nhan_vien", unique = true, nullable = false)
	public int getMaNhanVien() {
		return this.maNhanVien;
	}

	public void setMaNhanVien(int maNhanVien) {
		this.maNhanVien = maNhanVien;
	}

	@Column(name = "enabled")
	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

}
